name: build steam
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - steamcmd/**
jobs:
  push:
    name: "yolks:steamcmd_debian"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./steamcmd
          file: ./steamcmd/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/rampart-games-limited/yolks:steamcmd_debian-slim'
      - uses: docker/build-push-action@v4
        with:
          context: ./steamcmd
          file: ./steamcmd/valheim/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/rampart-games-limited/yolks:steamcmd_debian-slim-valheim
